# Set time-stamp variables 
--- 
- name: Create date and timestamp 
  hosts: welo03 

  pre_tasks: 
# Code for start and end time  

   - name: Get start and stop time 

     set_fact: 
       stop_time: "2022-05-07 08:08:08" 
       start_time: "2022-05-06 08:08:08" 
       zero_time: "1970-01-01 00:00:00" 

   - name: Get start and stop time variables 

     set_fact: 

       start_time_days: "{{ ((start_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).days }}" 
       stop_time_days: "{{ ((stop_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).days }}" 

   - name: Iteration list 
     debug: msg="Iteration {{ item }}" 
     with_sequence: start={{ ( start_time_days ) }} end={{ stop_time_days }} stride=1 

   - name: Timestamp - start time and date 
     debug: 
       msg: "start_time_days={{ ( start_time_days ) }} stop_time_days={{ stop_time_days }} }}" 

# Define dir path as variable - inserted part

   - name: define dir path as variable
     set_fact: 
       mon_sar_path: /var/log/sa/

# continue on dir path to add sa file plus number for days

   - set_fact: 
       v_file_list: "{{ v_file_list | default([]) + [ ( mon_sar_path + 'sa' + ( '%d' | strftime(86400 * item | int))) ] }}" 

     with_sequence: start={{ ( start_time_days ) }} end={{ stop_time_days }} stride=1 

   - debug: 
       msg: "v_file_list={{ v_file_list }}" 

       # Remove old file 

   - name : remove old file 
     shell: "rm -f ~/tmp/SAT_CPU.csv" 

# Get files and Shell command sadf  

   - name: Get files
     set_fact:  
       v_sa_files: "{{ v_file_list }}" 
       register: v_sa_files 

   - name: Create csv file 
     shell: sadf -d {{ item }} -- | sed '/^#/ d' | sed '1d' | sed 's/;/,/g' >> ~/tmp/SAT_CPU.csv 
     loop: "{{ v_sa_files }}"  

# Fetch files from welo03 server 
   
   - name: fetch SAT_CPU.csv files
     fetch:
       src: /home/tcuser/tmp/SAT_CPU.csv
       dest: fetched/prefix-{{ inventory_hostname }}
       flat: yes