# Set time-stamp variables 
--- 
- name: Create date and timestamp 
  hosts: localhost 

  pre_tasks: 
# Code for start and end time  

   - name: Get start and stop time 

     set_fact: 
       stop_time: "2022-05-07 08:08:08" 
       start_time: "2022-05-06 08:08:08" 
       zero_time: "1970-01-01 00:00:00" 

   - name: Get start and stop time variables 

     set_fact: 

       start_time_days: "{{ ((start_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).days }}" 
       stop_time_days: "{{ ((stop_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).days }}" 

   - name: Iteration list 
     debug: msg="Iteration {{ item }}" 
     with_sequence: start={{ ( start_time_days ) }} end={{ stop_time_days }} stride=1 

   - name: Timestamp - start time and date 
     debug: 
       msg: "start_time_days={{ ( start_time_days ) }} stop_time_days={{ stop_time_days }} }}" 

# Define dir path as variable - inserted part

   - name: define dir path as month variable
     set_fact: 
       mon_sar_path: /var/log/sa/
       register: mon_sar_path

   - name: define dir path as day variable
     set_fact: 
       day_sar_path: sa
       register: day_sar_path

# continue on dir path to add sa file plus number for days

   - set_fact: 
       v_file_list: "{{ v_file_list | default([]) + [ ( mon_sar_path + day_sar_path + ( '%d' | strftime(86400 * item | int))) ] }}" 

     with_sequence: start={{ ( start_time_days ) }} end={{ stop_time_days }} stride=1 

   - debug: 
       msg: "v_file_list={{ v_file_list }}" 


       # Remove old file 

   - name : remove old file 
     shell: "rm -f ~/tc_simul/reports/STAT_CPU.csv" 

# Get files and Shell command sadf  

   - name: Get files
     set_fact:  
       v_sa_files: "{{ v_file_list }}" 
       register: v_sa_files 

   - name: Create csv file 
     shell: sadf -d {{ item }} -- | sed '/^#/ d' | sed '1d' | sed 's/;/,/g' >> ~/tc_simul/reports/STAT_CPU.csv 
     loop: "{{ v_sa_files }}"  

# Combine 2 csv files - Header + concatenated data
   - name : Add two csv files
     shell: cat HEADER_STAT_CPU.csv > combined1a.csv && tail -n+3 ~/tc_simul/reports/STAT_CPU.csv >> combined1a.csv

# use awk to create Stats for column 5 %user in file stats.txt
# awk -F "," 'BEGIN { s=0;n=0; } NR>1 { s=s+$5;n++; k=k+$5*5 } 
# END{print "STATS for %user = ", "Sum=",s, "Records=",n, "Mean=",s/n, "STDev=",sqrt((k-s)/(n-1)) > stats.txt}' combined1a.csv 
#
# awk '{if($2!=""){count++;sum+=$2};y+=$2^2} END{sq=sqrt(y/NR-(sum/NR)^2);sq=sq?sq:0;print "Mean = "sum/count ORS "S.D = ",sq}'  Input_file
# stdev = sqrt((1/N)*(sum of (value - mean)^2))

   - name : Create stats file 
     shell: awk -F "," 'BEGIN { sum=0;n=0; } NR>1 { sum=sum+$5;n++; k=k+$5^2 } END{sq=sqrt(k/NR-(sum/NR)^2);sq=sq?sq:0;print "STATS for %user:", "Sum=",sum, "Records=",n, "Mean=",sum/n, "STDev=",sq > "stats.txt"}' ~/tc_simul/reports/STAT_CPU.csv 
# append stats file 
   - name : Append min and max to stats file 
     shell: awk -F "," '{if(min==""){min=max=$5}; if($5>max) {max=$5}; if($5<min) {min=$5}} END{print "STATS for %user:", "Max value=",max, "Min value=",min >> "stats.txt"}' ~/tc_simul/reports/STAT_CPU.csv
 



