# Set time-stamp variables 
--- 
- name: Create date and timestamp 
  hosts: localhost 

  pre_tasks: 
# Code for start and end time  

   - name: Get start and stop time 

     set_fact: 
       stop_time: "2022-05-12 22:21:33" 
       start_time: "2022-05-12 22:21:40" 
       zero_time: "1970-01-01 00:00:00" 

   - name: Get start and stop time variables 

     set_fact: 

       start_time_days: "{{ ((start_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).days }}" 
       stop_time_days: "{{ ((stop_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).days }}" 

   - name: Iteration list 
     debug: msg="Iteration {{ item }}" 
     with_sequence: start={{ ( start_time_days ) }} end={{ stop_time_days }} stride=1 

   - name: Timestamp - start time and date 
     debug: 
       msg: "start_time_days={{ ( start_time_days ) }} stop_time_days={{ stop_time_days }} divljak={{ '%Y-%m-%d 00:00:00' | strftime(0) }}" 

#Get variables for start_sec and Stop_sec

   - name: Get start_sec and stop_sec time variables 
     set_fact: 
       start_sec: "{{ ((start_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).total_seconds() }}" 
       stop_sec: "{{ ((stop_time | to_datetime) - (zero_time | to_datetime('%Y-%m-%d %H:%M:%S'))).total_seconds() }}" 

   - debug: msg="start_sec={{ ( start_sec ) }} stop_sec={{ stop_sec }} }}" 


# Define time stamps for stop and start time in sec since the Epoch - inserted part


   - name: timestamp stop_sec
     shell: echo "{{ start_time }}" | awk '{ split($0,a,/(-| |:)/); print mktime(sprintf("%04d %02d %02d %02d %02d %02d",a[1],a[2],a[3],a[4],a[5],a[6])) > "reports/timesec.txt" }' 

   - name: timestamp start_sec
     shell: echo "{{ stop_time }}" | awk '{ split($0,a,/(-| |:)/); print mktime(sprintf("%04d %02d %02d %02d %02d %02d",a[1],a[2],a[3],a[4],a[5],a[6])) >> "reports/timesec.txt" }' 
  

   